- name: Configure mpv for Linux
  include: linux.yml
  when: ansible_distribution | lower | search('linux')

- name: Configure mpv for Mac
  include: mac.yml
  when: ansible_distribution | lower | search('mac')

