- hosts: '{{ host }}'
  become: True
  become_user: '{{ user }}'
  roles:
    - { role: zshrc, tags: zshrc }
    - { role: zprofile, tags: zprofile }
    - { role: tmux, tags: tmux }
    - { role: neovim, tags: neovim }
    - { role: gitconfig, tags: gitconfig }
    - { role: kitty, tags: kitty }
    - { role: mpv, tags: mpv }
    - { role: qutebrowser, tags: qutebrowser }

