- name: Configure qutebrowser on Linux
  include: linux.yml
  when: ansible_distribution | lower is search('linux')

- name: Configure qutebrowser on Mac
  include: mac.yml
  when: ansible_distribution | lower is search('mac')

