- name: Set configuration directory for Linux
  include: linux.yml
  when: ansible_distribution | lower is search('linux')

- name: Set configuration directory for Mac
  include: mac.yml
  when: ansible_distribution | lower is search('mac')

