- name: Create or clear zshrc configuration directory
  file:
    path: ~/.zshrc.d/
    state: '{{ item }}'
  with_items:
    - absent
    - directory

- name: Copy Linux zshrc configuration
  copy:
    src: '{{ item }}/'
    dest: ~/.zshrc.d/
  with_items:
    - common
    - linux
  when: ansible_distribution | lower | search('linux')

- name: Copy Mac zshrc configuration
  copy:
    src: '{{ item }}/'
    dest: ~/.zshrc.d/
  with_items:
    - common
    - mac
  when: ansible_distribution | lower | search('mac')

- name: Create .zshrc from template
  template:
    src: zshrc
    dest: ~/.zshrc

- name: Create Zsh prompts configuration file from template
  template:
    src: 55-prompts.zsh
    dest: ~/.zshrc.d/

- name: Add custom entries to zshrc
  blockinfile:
    path: ~/.zshrc
    insertafter: '^# Ansible-managed$'
    marker: '# {mark} Ansible-managed block: Add custom entries'
    block: '{{ zshrc.custom }}'
  when: zshrc.custom is defined
