- name: Create kitty configuration directory
  file:
    path: '{{ config_dir }}/kitty/'
    state: directory

- name: Create kitty configuration file from template
  template:
    src: kitty.conf
    dest: '{{ config_dir }}/kitty/kitty.conf'
