- name: Create GTK+ 3 configuration directory
  file:
    path: '{{ config_dir }}/gtk-3.0/'
    state: directory

- name: Create GTK+ 3 configuration files from templates
  template:
    src: '{{ item }}'
    dest: '{{ config_dir }}/gtk-3.0/{{ item }}'
  with_items: 
    - gtk.css
    - settings.ini
