- name: Create Neovim configuration directories
  file:
    path: ~/.config/nvim/colors/
    state: directory

- name: Copy Neovim configuration file
  copy:
    src: init.vim
    dest: ~/.config/nvim/

- name: Download gruvbox colour scheme
  command: >
    curl
    https://raw.githubusercontent.com/morhetz/gruvbox/master/colors/gruvbox.vim
    -o ~/.config/nvim/colors/gruvbox.vim
  args:
    warn: False

