- name: Configure qutebrowser on Linux
  include: linux.yml
  when: ansible_distribution | lower | search('linux')

- name: Configure qutebrowser on Mac
  include: mac.yml
  when: ansible_distribution | lower | search('mac')

- name: Create ~/git/ directory (required for following git clone task)
  file:
    path: ~/git/
    state: directory

- name: Clone otsaloma's markdown-css repository (for GitHub Markdown previews)
  git:
    repo: https://github.com/otsaloma/markdown-css.git
    dest: ~/git/markdown-css/

